import{a as S,S as q,i as u}from"./assets/vendor-BK_rxH-O.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const M="https://pixabay.com/api/",B="19018033-87a1a51fb4261bc6ee99901a2",E=15;let l=1;async function m(r){try{return(await S.get(M,{params:{key:B,q:r,image_type:"photo",orientation:"horizontal",safesearch:"true",page:l,per_page:E}})).data}catch(t){throw console.log("Помилка при отриманні зображень:",t.message),t}}function R(){l=1}function g(){l++}const p=document.querySelector(".gallery"),y=document.querySelector(".loader"),f=document.querySelector(".load-more-btn");let $=new q(".gallery a",{captionsData:"alt",captionDelay:250});function b(r){const t=r.map(({webformatURL:s,largeImageURL:n,tags:e,likes:o,views:c,comments:w,downloads:P})=>`<div class="gallery-list">
          <a class="gallery-item" href="${n}">
          <div class="cart-item">
            <img src="${s}" alt="${e}" loading="lazy">
              <div class="info">
                <p class="info-item"><b>Likes:</b>${o}</p>
                <p class="info-item"><b>Views:</b>${c}</p>
                <p class="info-item"><b>Comments:</b>${w}</p>
                <p class="info-item"><b>Downloads:</b>${P}</p>
              </div>
            </div>
          </a>
        </div>`).join("");p.insertAdjacentHTML("beforeend",t),$.refresh()}function O(){p.innerHTML=""}function L(){y.classList.remove("hidden")}function a(){y.classList.add("hidden")}function v(){f.classList.remove("hidden")}function i(){f.classList.add("hidden")}const h=document.querySelector(".form"),x=h.elements["search-text"];let d="";h.addEventListener("submit",A);async function A(r){r.preventDefault();const t=x.value.trim();if(!t){u.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}d=t,R(),O(),L(),i();try{const s=await m(d);if(s.hits.length===0){a(),u.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}b(s.hits),a(),g();const n=Math.ceil(s.totalHits/15);l<n?v():i(),h.reset()}catch(s){a(),i(),console.error(s)}}f.addEventListener("click",_);async function _(){L();try{const r=await m(d);if(r.hits.length===0){a(),u.warning({message:"We are sorry, but you have reached the end of search results.",position:"topRight"}),i();return}b(r.hits),a(),g();const t=Math.ceil(r.totalHits/15);l>=t?(u.warning({message:"We are sorry, but you have reached the end of search results.",position:"topRight"}),i()):v(),D()}catch(r){a(),i(),console.error(r)}}function D(){const r=document.querySelector(".gallery-list");if(!r)return;const{height:t}=r.getBoundingClientRect();window.scrollBy({top:t*2,left:0,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
