import{a as S,S as P,i as d}from"./assets/vendor-BK_rxH-O.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function o(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(e){if(e.ep)return;e.ep=!0;const s=o(e);fetch(e.href,s)}})();const q="https://pixabay.com/api/",M="19018033-87a1a51fb4261bc6ee99901a2",B=15;async function m(t,r){try{return(await S.get(q,{params:{key:M,q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",page:r,per_page:B}})).data}catch(o){throw console.log("Помилка при отриманні зображень:",o.message),o}}const p=document.querySelector(".gallery"),y=document.querySelector(".loader"),h=document.querySelector(".load-more-btn");let E=new P(".gallery a",{captionsData:"alt",captionDelay:250});function g(t){const r=t.map(({webformatURL:o,largeImageURL:i,tags:e,likes:s,views:l,comments:v,downloads:w})=>`<div class="gallery-list">
          <a class="gallery-item" href="${i}">
          <div class="cart-item">
            <img src="${o}" alt="${e}" loading="lazy">
              <div class="info">
                <p class="info-item"><b>Likes:</b>${s}</p>
                <p class="info-item"><b>Views:</b>${l}</p>
                <p class="info-item"><b>Comments:</b>${v}</p>
                <p class="info-item"><b>Downloads:</b>${w}</p>
              </div>
            </div>
          </a>
        </div>`).join("");p.insertAdjacentHTML("beforeend",r),E.refresh()}function R(){p.innerHTML=""}function b(){y.classList.remove("hidden")}function n(){y.classList.add("hidden")}function L(){h.classList.remove("hidden")}function c(){h.classList.add("hidden")}const f=document.querySelector(".form"),$=f.elements["search-text"];let u="",a=1;f.addEventListener("submit",O);async function O(t){t.preventDefault();const r=$.value.trim();if(!r){d.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}u=r,a=1,R(),b(),c();try{const o=await m(u,a);if(o.hits.length===0){n(),d.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}g(o.hits),n();const i=Math.ceil(o.totalHits/15);a<i?L():c(),a++,f.reset()}catch(o){n(),c(),console.error(o)}}h.addEventListener("click",x);async function x(){b();try{const t=await m(u,a);if(t.hits.length===0){n(),d.warning({message:"We are sorry, but you have reached the end of search results.",position:"topRight"}),c();return}g(t.hits),n();const r=Math.ceil(t.totalHits/15);a>=r?(d.warning({message:"We are sorry, but you have reached the end of search results.",position:"topRight"}),c()):L(),a++,A()}catch(t){n(),c(),console.error(t)}}function A(){const t=document.querySelector(".gallery-list");if(!t)return;const{height:r}=t.getBoundingClientRect();window.scrollBy({top:r*2,left:0,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
