import{a as P,S as q,i as u}from"./assets/vendor-BK_rxH-O.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const M="https://pixabay.com/api/",B="19018033-87a1a51fb4261bc6ee99901a2",E=15;let l=1;async function h(r){try{return(await P.get(M,{params:{key:B,q:r,image_type:"photo",orientation:"horizontal",safesearch:"true",page:l,per_page:E}})).data}catch(t){throw console.log("Помилка при отриманні зображень:",t.message),t}}function $(){l=1}function p(){l++}const y=document.querySelector(".gallery"),g=document.querySelector(".loader"),f=document.querySelector(".load-more-btn");let O=new q(".gallery a",{captionsData:"alt",captionDelay:250});function b(r){const t=r.map(({webformatURL:s,largeImageURL:a,tags:e,likes:o,views:n,comments:w,downloads:S})=>`<div class="gallery-list">
          <a class="gallery-item" href="${a}">
          <div class="cart-item">
            <img src="${s}" alt="${e}" loading="lazy">
              <div class="info">
                <p class="info-item"><b>Likes:</b>${o}</p>
                <p class="info-item"><b>Views:</b>${n}</p>
                <p class="info-item"><b>Comments:</b>${w}</p>
                <p class="info-item"><b>Downloads:</b>${S}</p>
              </div>
            </div>
          </a>
        </div>`).join("");y.insertAdjacentHTML("beforeend",t),O.refresh()}function R(){y.innerHTML=""}function L(){g.classList.remove("hidden")}function i(){g.classList.add("hidden")}function v(){f.classList.remove("hidden")}function c(){f.classList.add("hidden")}const m=document.querySelector(".form"),x=m.elements["search-text"];let d="";m.addEventListener("submit",A);async function A(r){r.preventDefault();const t=x.value.trim();if(!t){u.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}d=t,$(),R(),L(),c();try{const s=await h(d);if(b(s.hits),i(),s.hits.length===0){u.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}else p(),v();m.reset()}catch(s){i(),c(),console.error(s)}}f.addEventListener("click",_);async function _(){L();try{const r=await h(d);b(r.hits),i();const t=Math.ceil(r.totalHits/15);if(l>=t){u.warning({message:"We are sorry, but you have reached the end of search results.",position:"topRight"}),c();return}else p(),v();D()}catch(r){i(),c(),console.error(r)}}function D(){const r=document.querySelector(".gallery-list");if(!r)return;const{height:t}=r.getBoundingClientRect();window.scrollBy({top:t*2,left:0,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
